name: CI

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

permissions: {}

jobs:
  check:
    permissions:
      contents: read
    uses: studiobimo/.github/.github/workflows/ci-java-gradle.yml@v1
    with:
      gradle-tasks: check
      artifact-paths: |
        fabric/build/libs/*.jar
        neoforge/build/libs/*.jar
